"""add_media_fields_and_portfolio_table

Revision ID: 841f15dd0f88
Revises: 88ac1744563a
Create Date: 2025-11-21 01:36:16.782958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841f15dd0f88'
down_revision: Union[str, None] = '88ac1744563a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_images_id'), 'portfolio_images', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_images_user_id'), 'portfolio_images', ['user_id'], unique=False)
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('banner_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner_url')
    op.drop_column('users', 'avatar_url')
    op.drop_index(op.f('ix_portfolio_images_user_id'), table_name='portfolio_images')
    op.drop_index(op.f('ix_portfolio_images_id'), table_name='portfolio_images')
    op.drop_table('portfolio_images')
    # ### end Alembic commands ###

