"""add_artist_profile_fields

Revision ID: 9b0a1c2d3e45
Revises: 841f15dd0f88
Create Date: 2025-11-21 02:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "9b0a1c2d3e45"
down_revision: Union[str, None] = "841f15dd0f88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artists", sa.Column("about", sa.Text(), nullable=True))
    op.add_column(
        "artists",
        sa.Column(
            "styles",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.add_column("artists", sa.Column("city", sa.String(), nullable=True))
    op.add_column("artists", sa.Column("studio_id", sa.Integer(), nullable=True))
    op.add_column("artists", sa.Column("session_price", sa.Integer(), nullable=True))
    op.add_column("artists", sa.Column("instagram", sa.String(), nullable=True))
    op.add_column("artists", sa.Column("telegram", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artists", "telegram")
    op.drop_column("artists", "instagram")
    op.drop_column("artists", "session_price")
    op.drop_column("artists", "studio_id")
    op.drop_column("artists", "city")
    op.drop_column("artists", "styles")
    op.drop_column("artists", "about")
    # ### end Alembic commands ###


